---
- name: install ius-release
  become: yes
  yum:
    name:
      - https://repo.ius.io/ius-release-el7.rpm

- name: disable ius
  become: yes
  replace:
    path: /etc/yum.repos.d/ius.repo
    regexp: "^enabled.+$"
    replace: "enabled = 0"

- name: install git224
  become: yes
  yum:
    name:
      - git224
    enablerepo: ius
