---
- name: create data directory
  file:
    path: "{{ data_dir }}"
    state: directory

- name: check sqlite3 path
  stat:
    path: "{{ sqlite3_exec_path }}"
  register: exec_path

- name: check src url
  stat:
    path: "{{ sqlite3_src_url_file }}"
  register: src_url_file

- name: get src url
  slurp:
    src: "{{ sqlite3_src_url_file }}"
  register: src_url
  when: src_url_file.stat.exists

- name: check src url changed
  set_fact:
    build_require: "{{ (not exec_path.stat.exists) or (src_url.content is not defined) or ((src_url.content | b64decode) != sqlite3_src_url) }}"

- name: create build directory
  tempfile:
    state: directory
    prefix: "{{ sqlite3_build_dir_prefix }}"
  register: build_dir
  when: build_require

- name: download src
  get_url:
    url: "{{ sqlite3_src_url }}"
    dest: "{{ build_dir.path }}/{{ sqlite3_src_file_name }}"
  register: src_file
  when: build_require

- name: extract src file
  unarchive:
    src: "{{ src_file.dest }}"
    dest: "{{ build_dir.path }}"
    copy: no
    extra_opts: "--strip-components=1"
  when: build_require

- name: configure
  command:
    argv:
      - "./configure"
      - "--prefix=/usr/local"
    chdir: "{{ build_dir.path }}"
  when: build_require

- name: make
  command:
    cmd: make
    chdir: "{{ build_dir.path }}"
  when: build_require

- name: install
  become: yes
  command:
    cmd: make install
    chdir: "{{ build_dir.path }}"
  when: build_require

- name: exec ldconfig
  become: yes
  command: ldconfig
  when: build_require

- name: save src url
  copy:
    content: "{{ src_file.url }}"
    dest: "{{ sqlite3_src_url_file }}"
  when: build_require

- name: save src checksum
  copy:
    content: "{{ src_file.checksum_src }}"
    dest: "{{ sqlite3_checksum_file }}"
  when: build_require
