---
- name: sqlite3-centos7
  include_tasks: sqlite3-centos7.yml
  when: _centos7

- name: sqlite3-centos8
  include_tasks: sqlite3-centos8.yml
  when: _centos8

- name: sqlite3-ubuntu
  include_tasks: sqlite3-ubuntu.yml
  when: _ubuntu20
