---
- name: sqlite3-centos7
  include_tasks: sqlite3-centos7-main.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_pkg_mgr == 'yum'

- name: sqlite3-centos8
  include_tasks: sqlite3-centos8-main.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_pkg_mgr == 'dnf'
