---
- name: install epel
  become: yes
  yum:
    name:
      - epel-release

- name: install modules
  become: yes
  yum:
    name:
      - yum-utils
      - vim
      - wget
      - unzip
      - bzip2
      - jq
