---
- hosts: developer
  name: setup developer
  roles:
    - role: common
    - role: user-env
    - role: tools-utils
    - role: tools-develop
    - role: tools-system
    - role: dev-sqlite3
    - role: dev-nodenv
    - role: dev-pyenv
    - role: dev-vscode
    - role: service-docker
