---
- name: yum-install
  include_tasks: yum-install.yml

- name: git-centos7
  include_tasks: git-centos7-main.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- name: git-centos8
  include_tasks: git-centos8-main.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '8'

- name: ldconfig
  include_tasks: ldconfig.yml
