---
- name: chmod ~/.bash_profile
  file:
    path: ~/.bash_profile
    state: file
    mode: 0600

- name: edit ~/.bash_profile
  blockinfile:
    path: ~/.bash_profile
    backup: yes
    block: |
      if [ -d "${HOME}/.bash.d" ] ; then
        for f in "${HOME}"/.bash.d/*.sh ; do
          . "$f"
        done
        unset f
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK .bash.d"
    mode: 0600

- name: edit ~/.bashrc
  blockinfile:
    path: ~/.bashrc
    backup: yes
    block: |
      export PS1='\n[\u@\h \w]\n\$ '
      alias crontab='crontab -i'
      alias ll='ls -alF'
      alias la='ls -a'
      alias ..='cd ..'
    marker: "# {mark} ANSIBLE MANAGED BLOCK aliases"
    mode: 0600
