---
- name: bash-centos
  include_tasks: bash-centos.yml
  when: _centos7 or _centos8

- name: bash-ubuntu
  include_tasks: bash-ubuntu.yml
  when: _ubuntu20

- name: chmod ~/.bashrc
  file:
    path: ~/.bashrc
    state: file
    mode: 0600

- name: chmod ~/.bash_logout
  file:
    path: ~/.bash_logout
    state: file
    mode: 0600

- name: create ~/work
  file:
    path: ~/work
    state: directory
    mode: 0700

- name: create ~/.bash.d
  file:
    path: ~/.bash.d
    state: directory
    mode: 0700

- name: create 00-init.sh
  blockinfile:
    path: ~/.bash.d/00-init.sh
    block: |
      #
    create: yes
    mode: 0600

- name: edit ~/.vimrc
  blockinfile:
    path: ~/.vimrc
    backup: yes
    block: |
      colorscheme koehler
      set noautoindent
      set nopaste
      autocmd Filetype * set formatoptions-=ro
    create: yes
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    mode: 0600

- name: chmod ~/.pki
  file:
    path: ~/.pki
    state: directory
    mode: 0700
  when: _centos7 or _centos8
