---
- name: chmod ~/.bash_profile
  file:
    path: ~/.bash_profile
    state: file
    mode: 0600

- name: chmod ~/.bashrc
  file:
    path: ~/.bashrc
    state: file
    mode: 0600

- name: chmod ~/.bash_logout
  file:
    path: ~/.bash_logout
    state: file
    mode: 0600

- name: create ~/work
  file:
    path: ~/work
    state: directory
    mode: 0700

- name: create ~/.bash.d
  file:
    path: ~/.bash.d
    state: directory
    mode: 0700

- name: create 00-init.sh
  blockinfile:
    path: ~/.bash.d/00-init.sh
    block: |
      #
    create: yes
    mode: 0600

- name: edit ~/.bash_profile
  blockinfile:
    path: ~/.bash_profile
    backup: yes
    block: |
      if [ -d "${HOME}/.bash.d" ] ; then
        for f in "${HOME}"/.bash.d/*.sh ; do
          source "$f"
        done
        unset f
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK .bash.d"
    mode: 0600

- name: edit ~/.bashrc
  blockinfile:
    path: ~/.bashrc
    backup: yes
    block: |
      export PS1='\n[\u@\h \w]\n\$ '
      alias crontab='crontab -i'
      alias ll='ls -alF'
      alias la='ls -a'
      alias ..='cd ..'
    marker: "# {mark} ANSIBLE MANAGED BLOCK aliases"
    mode: 0600

- name: edit ~/.vimrc
  blockinfile:
    path: ~/.vimrc
    backup: yes
    block: |
      colorscheme koehler
      set noautoindent
    create: yes
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    mode: 0600

- name: chmod ~/.pki
  file:
    path: ~/.pki
    state: directory
    mode: 0700
