---
- name: get yum installed
  yum:
    list: installed
  register: _yum_installed

- name: uninstal @base git
  become: yes
  yum:
    name:
      - "git*"
    state: absent
  when: "_yum_installed.results | map(attribute='name') | unique | select('match', '^git$')"

- name: install ius-release
  become: yes
  yum:
    name:
      - https://repo.ius.io/ius-release-el7.rpm

- name: disable ius
  become: yes
  replace:
    path: /etc/yum.repos.d/ius.repo
    regexp: "^enabled.+$"
    replace: "enabled = 0"

- name: install git224
  become: yes
  yum:
    name:
      - git224
    enablerepo: ius
