---
- name: uninstall old version
  become: yes
  apt:
    name:
      - docker
      - docker-engine
      - docker-common
      - docker.io
      - containerd
      - runc
    state: absent

- name: install package
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: add apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: install apt repos
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: install docker-ce
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
