---
- name: check os
  set_fact:
    _centos: "{{ (ansible_os_family == 'RedHat') and (ansible_distribution_major_version in ['7','8']) }}"

- name:
  fail:
    msg: "not supported"
  when: not _centos
