---
- name: pyenv clean if clean flag is yes
  file:
    path: "{{ pyenv_root }}"
    state: absent
  when: pyenv_clean

- name: git clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_root }}"
    depth: 1

- name: git clone pyenv-update
  git:
    repo: https://github.com/pyenv/pyenv-update.git
    dest: "{{ pyenv_root }}/plugins/pyenv-update"
    depth: 1

- name: chmod pyenv root
  file:
    path: "{{ pyenv_root }}"
    state: directory
    mode: 0700

- name: create 30-pyenv.sh
  blockinfile:
    path: ~/.bash.d/30-pyenv.sh
    block: |
      export PYENV_ROOT="{{ pyenv_root }}"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
    create: yes
    mode: 0600

- name: check install require
  stat:
    path: "{{ pyenv_root }}/versions/{{ python_version }}"
  register: _python
  changed_when: not _python.stat.exists

- name: pyenv update
  shell: |
    source ~/.bash.d/30-pyenv.sh
    pyenv update
  when: not _python.stat.exists

- name: install python
  shell: |
    source ~/.bash.d/30-pyenv.sh
    pyenv install {{ python_version }}
  when: not _python.stat.exists

- name: get global python version
  shell: |
    source ~/.bash.d/30-pyenv.sh
    pyenv global
  register: _pyenv_global
  check_mode: no
  changed_when: _pyenv_global.stdout != python_version

- name: change global
  shell: |
    source ~/.bash.d/30-pyenv.sh
    pyenv global {{ python_version }}
    pyenv rehash
  when: _pyenv_global.stdout != python_version
