---
- name: create nginx.repo
  become: yes
  blockinfile:
    path: /etc/yum.repos.d/nginx.repo
    block: |
      [nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true
    create: yes
    mode: 0644

- name: install nginx
  become: yes
  yum:
    name:
      - nginx

- name: start nginx
  become: yes
  systemd:
    name: nginx
    state: started
    enabled: yes
